name: Generate PDF of Theoretical
run-name: Generating PDF of Theoretical
on: [push]
jobs:
  generate-theoretical:
    runs-on: ubuntu-latest
    steps:
      - name: install latex packages
        run: sudo apt install texlive texinfo texlive-fonts-recommended texlive-latex-extra

      - name: execute generate_theoretical.py
        run: python ./generate_latex/generate_theoretical.py